name: Trigger AWS Lamba
author: Abhinav Khanna
description: This action invokes AWS Lambda from github. you can use a scheduled job or on git teiggers. 
inputs: 
  endpoint:
   description: The endpoint URI to send requests to. The default endpoint is built from the configured region. The endpoint should be a string like 'https://{service}.{region}.amazonaws.com'.
   required: False
   default: Null
  accessKeyId: 
    description: your AWS access key ID.
    required: False
    default: Null
  secretAccessKey: 
    description: your AWS secret access key.
    required: False
    default: Null
  sessionToken:
    description: the optional AWS session token to sign requests with.
    required: False
    default: Null
  region:
    description:  the region to send service requests to. See AWS.Lambda.region for more information.
    required: False
    default: Null
  maxRetries:
    description: the maximum amount of retries to attempt with a request. See AWS.Lambda.maxRetries for more information.
    required: False
    default: Null
  maxRedirects:
    description:  the maximum amount of redirects to follow with a request. See AWS.Lambda.maxRedirects for more information.
    required: False
    default: Null
  sslEnabled:
    description: whether to enable SSL for requests.
    required: False
    default: Null
  functionName:
    description: The name of the Lambda function, version, or alias.
    required: True
  invocationType:
    description: | 
      RequestResponse (default) - Invoke the function synchronously. Keep the connection open until the function returns a response or times out. The API response includes the function response and additional data.
      Event - Invoke the function asynchronously. Send events that fail multiple times to the function's dead-letter queue (if it's configured). The API response only includes a status code.
      DryRun - Validate parameter values and verify that the user or role has permission to invoke the function.
      Possible values include:
        "Event"
        "RequestResponse"
        "DryRun"
    required: False
    default: "RequestResponse"
  logType:
    description: | 
      Set to Tail to include the execution log in the response.
      Possible values include:
        "None"
        "Tail"
    required: False
    default: "None"
  clientContext:
    description: Up to 3583 bytes of base64-encoded data about the invoking client to pass to the function in the context object.
    required: False
    default: Null
  payload:
    description: The JSON that you want to provide to your Lambda function as input
    required: False
    default: Null
  qualifier:
    description: Specify a version or alias to invoke a published version of the function.
    required: False
    default: Null

    
runs:
  using: 'node12'
  main:  'dist/index.js'

branding:
  icon: 'grid'  
  color: 'blue'